require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BlackPlanet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Firebase/Analytics'
  
  pod "ComScore/Static"

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-ad-manager', path: '../node_modules/react-native-ad-manager'

  target 'BlackPlanetTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BlackPlanet-tvOS' do
  # Pods for BlackPlanet-tvOS

  target 'BlackPlanet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
